#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEST_ROOT="$(mktemp -d)"
trap 'rm -rf "$TEST_ROOT"' EXIT

fail() {
  printf 'runtime test failed: %s\n' "$*" >&2
  exit 1
}

mkdir -p "$TEST_ROOT/maodie/config" "$TEST_ROOT/maodie/kernel" "$TEST_ROOT/maodie/run"

cat > "$TEST_ROOT/maodie/config/config.yaml" <<'YAML'
ipv6: true
external-controller: 127.0.0.1:9090
secret: ""
tun:
  enable: true
  device: testtun
  auto-route: true
proxy-providers:
  nested:
    secret: "nested-value"
YAML

network_config=$(MAODIE_MOD_DIR="$TEST_ROOT" sh "$ROOT_DIR/maodie/scripts/network.sh" config)
grep -Fxq 'tun_enable=true' <<<"$network_config" || fail 'tun.enable was not parsed'
grep -Fxq 'tun_device=testtun' <<<"$network_config" || fail 'tun.device was not parsed'
grep -Fxq 'tun_auto_route=true' <<<"$network_config" || fail 'tun.auto-route was not parsed'
grep -Fxq 'ipv6=true' <<<"$network_config" || fail 'top-level ipv6 was not parsed'

cat > "$TEST_ROOT/maodie/kernel/Mihomo" <<'SH'
#!/bin/sh
candidate=""
while [ "$#" -gt 0 ]; do
  if [ "$1" = "-f" ]; then
    shift
    candidate="$1"
  fi
  shift
done
[ -n "$candidate" ] || exit 2
grep -q 'INVALID_CONFIG' "$candidate" 2>/dev/null && exit 1
exit 0
SH
chmod 700 "$TEST_ROOT/maodie/kernel/Mihomo"

set +e
secret=$(MAODIE_MOD_DIR="$TEST_ROOT" sh "$ROOT_DIR/maodie/scripts/configctl.sh" ensure-secret --changed-exit-code)
secret_status=$?
set -e
[[ "$secret_status" -eq 10 ]] || fail "first ensure-secret returned $secret_status instead of 10"
[[ "$secret" =~ ^[A-Za-z0-9._~-]+$ ]] || fail 'generated secret is unsafe'
grep -Fqx "secret: \"$secret\"  # generated by configctl.sh; keep private" \
  "$TEST_ROOT/maodie/config/config.yaml" || fail 'top-level secret was not written'
grep -Fqx '    secret: "nested-value"' "$TEST_ROOT/maodie/config/config.yaml" \
  || fail 'nested secret was modified'

set +e
second_secret=$(MAODIE_MOD_DIR="$TEST_ROOT" sh "$ROOT_DIR/maodie/scripts/configctl.sh" ensure-secret --changed-exit-code)
second_status=$?
set -e
[[ "$second_status" -eq 0 ]] || fail "idempotent ensure-secret returned $second_status"
[[ "$second_secret" = "$secret" ]] || fail 'idempotent ensure-secret changed the value'

cp "$TEST_ROOT/maodie/config/config.yaml" "$TEST_ROOT/before-apply.yaml"
cat > "$TEST_ROOT/candidate.yaml" <<EOF
ipv6: false
external-controller: 127.0.0.1:9090
secret: "$secret"
tun:
  enable: false
marker: applied
EOF
payload=$(base64 < "$TEST_ROOT/candidate.yaml" | tr -d '\n')
MAODIE_MOD_DIR="$TEST_ROOT" sh "$ROOT_DIR/maodie/scripts/configctl.sh" apply-base64 "$payload"
cmp -s "$TEST_ROOT/before-apply.yaml" "$TEST_ROOT/maodie/config/config.yaml.last-good" \
  || fail 'last-good was not saved atomically from the previous config'
grep -Fxq 'marker: applied' "$TEST_ROOT/maodie/config/config.yaml" || fail 'valid config was not applied'

printf '%s\n' 'INVALID_CONFIG' > "$TEST_ROOT/invalid.yaml"
invalid_payload=$(base64 < "$TEST_ROOT/invalid.yaml" | tr -d '\n')
if MAODIE_MOD_DIR="$TEST_ROOT" sh "$ROOT_DIR/maodie/scripts/configctl.sh" \
    apply-base64 "$invalid_payload" >/dev/null 2>&1; then
  fail 'invalid config was accepted'
fi
grep -Fxq 'marker: applied' "$TEST_ROOT/maodie/config/config.yaml" \
  || fail 'invalid update changed the active config'

MAODIE_MOD_DIR="$TEST_ROOT" sh "$ROOT_DIR/maodie/scripts/configctl.sh" restore
cmp -s "$TEST_ROOT/before-apply.yaml" "$TEST_ROOT/maodie/config/config.yaml" \
  || fail 'restore did not recover last-good'

cat > "$TEST_ROOT/unsupported-secret.yaml" <<'YAML'
external-controller: 127.0.0.1:9090
secret : "valid-yaml-but-noncanonical"
YAML
cp "$TEST_ROOT/unsupported-secret.yaml" "$TEST_ROOT/maodie/config/config.yaml"
if MAODIE_MOD_DIR="$TEST_ROOT" sh "$ROOT_DIR/maodie/scripts/configctl.sh" \
    ensure-secret >/dev/null 2>&1; then
  fail 'noncanonical top-level secret syntax was rewritten'
fi
cmp -s "$TEST_ROOT/unsupported-secret.yaml" "$TEST_ROOT/maodie/config/config.yaml" \
  || fail 'rejected secret syntax changed the config'

cat > "$TEST_ROOT/rejected-secret-write.yaml" <<'YAML'
external-controller: 127.0.0.1:9090
secret: ""
INVALID_CONFIG: true
YAML
cp "$TEST_ROOT/rejected-secret-write.yaml" "$TEST_ROOT/maodie/config/config.yaml"
if MAODIE_MOD_DIR="$TEST_ROOT" sh "$ROOT_DIR/maodie/scripts/configctl.sh" \
    ensure-secret >/dev/null 2>&1; then
  fail 'secret rewrite bypassed Mihomo validation'
fi
cmp -s "$TEST_ROOT/rejected-secret-write.yaml" "$TEST_ROOT/maodie/config/config.yaml" \
  || fail 'failed secret validation changed the config'

MOCK_BIN="$TEST_ROOT/mock-bin"
IPTABLES_LOG="$TEST_ROOT/iptables.log"
mkdir -p "$MOCK_BIN"
cat > "$MOCK_BIN/iptables" <<'SH'
#!/bin/sh
printf '%s\n' "$*" >> "$MAODIE_TEST_IPTABLES_LOG"
case " $* " in
  *' -w 2 -L '*) exit 0 ;;
  *' -C '*) exit 1 ;;
  *) exit 0 ;;
esac
SH
cp "$MOCK_BIN/iptables" "$MOCK_BIN/ip6tables"
chmod 700 "$MOCK_BIN/iptables" "$MOCK_BIN/ip6tables"

cp "$TEST_ROOT/before-apply.yaml" "$TEST_ROOT/maodie/config/config.yaml"
: > "$IPTABLES_LOG"
PATH="$MOCK_BIN:$PATH" MAODIE_TEST_IPTABLES_LOG="$IPTABLES_LOG" \
  MAODIE_MOD_DIR="$TEST_ROOT" MAODIE_TUN_WAIT_SECONDS=0 \
  sh "$ROOT_DIR/maodie/scripts/network.sh" apply >/dev/null 2>&1
grep -Fq -- '-A MAODIE_FWD -i testtun -j ACCEPT' "$IPTABLES_LOG" \
  || fail 'dedicated input rule was not applied'
grep -Fq -- '-A MAODIE_FWD -o testtun -j ACCEPT' "$IPTABLES_LOG" \
  || fail 'dedicated output rule was not applied'
grep -Fq -- '-I FORWARD 1 -j MAODIE_FWD' "$IPTABLES_LOG" \
  || fail 'dedicated chain jump was not applied'
if grep -Eq 'mangle|--mark|utun\\+' "$IPTABLES_LOG"; then
  fail 'network controller touched an unowned legacy rule'
fi

LIFECYCLE_ROOT="$TEST_ROOT/lifecycle"
mkdir -p "$LIFECYCLE_ROOT/maodie/config" "$LIFECYCLE_ROOT/maodie/kernel" \
  "$LIFECYCLE_ROOT/maodie/run" "$LIFECYCLE_ROOT/maodie/scripts"
printf '%s\n' 'mixed-port: 7890' > "$LIFECYCLE_ROOT/maodie/config/config.yaml"
printf '%s\n' 'fake kernel' > "$LIFECYCLE_ROOT/maodie/kernel/Mihomo"
cat > "$LIFECYCLE_ROOT/maodie/scripts/core.sh" <<'SH'
#!/bin/sh
printf 'core:%s\n' "$1" >> "$MAODIE_MOD_DIR/maodie/run/lifecycle.calls"
exit 0
SH
cat > "$LIFECYCLE_ROOT/maodie/scripts/monitor.sh" <<'SH'
#!/bin/sh
printf 'monitor\n' >> "$MAODIE_MOD_DIR/maodie/run/lifecycle.calls"
exit 0
SH
cat > "$LIFECYCLE_ROOT/maodie/scripts/NoAdsService.sh" <<'SH'
#!/bin/sh
printf 'adblock:%s\n' "$1" >> "$MAODIE_MOD_DIR/maodie/run/lifecycle.calls"
exit 0
SH
cp "$LIFECYCLE_ROOT/maodie/scripts/monitor.sh" "$LIFECYCLE_ROOT/maodie/scripts/configctl.sh"
cp "$LIFECYCLE_ROOT/maodie/scripts/monitor.sh" "$LIFECYCLE_ROOT/maodie/scripts/network.sh"
chmod 700 "$LIFECYCLE_ROOT/maodie/scripts/"*.sh
cat > "$MOCK_BIN/getprop" <<'SH'
#!/bin/sh
case "$1" in
  sys.boot_completed) printf '1\n' ;;
  ro.build.version.sdk) printf '34\n' ;;
esac
SH
chmod 700 "$MOCK_BIN/getprop"

PATH="$MOCK_BIN:$PATH" MAODIE_MOD_DIR="$LIFECYCLE_ROOT" \
  MAODIE_BOOT_TIMEOUT=0 MAODIE_POST_BOOT_DELAY=0 sh "$ROOT_DIR/service.sh"
printf '%s\n' 'preserve-pid' > "$LIFECYCLE_ROOT/maodie/run/kernel.pid"
printf '%s\n' 'preserve-sysctl' > "$LIFECYCLE_ROOT/maodie/run/sysctl.state"
PATH="$MOCK_BIN:$PATH" MAODIE_MOD_DIR="$LIFECYCLE_ROOT" \
  MAODIE_BOOT_TIMEOUT=0 MAODIE_POST_BOOT_DELAY=0 sh "$ROOT_DIR/service.sh"
grep -Fxq 'preserve-pid' "$LIFECYCLE_ROOT/maodie/run/kernel.pid" \
  || fail 'same-boot service re-entry discarded the PID state'
grep -Fxq 'preserve-sysctl' "$LIFECYCLE_ROOT/maodie/run/sysctl.state" \
  || fail 'same-boot service re-entry discarded the sysctl ledger'

PATH="$MOCK_BIN:$PATH" MAODIE_MOD_DIR="$LIFECYCLE_ROOT" sh "$ROOT_DIR/uninstall.sh" >/dev/null
[[ -d "$LIFECYCLE_ROOT" ]] || fail 'uninstall removed the module directory itself'
[[ -f "$LIFECYCLE_ROOT/maodie/run/maintenance" ]] \
  || fail 'uninstall did not retain the maintenance barrier'

RECOVERY_STATE="$TEST_ROOT/recovery.state"
printf '%s\n' '/data/data/invalid.example/cache/missing' > "$RECOVERY_STATE"
MAODIE_ASSUME_USER_UNLOCKED=1 MAODIE_ADBLOCK_STATE="$RECOVERY_STATE" \
  sh "$ROOT_DIR/maodie/scripts/adblock-recovery.sh" >/dev/null
[[ ! -e "$RECOVERY_STATE" ]] || fail 'standalone recovery did not clear a missing target'

printf 'Runtime tests passed.\n'
